### ISSUE TITLE
categories?

### ISSUE THREAD

**Issue by natalie-carlson** [gwcottle/rcrunchbase#9]
Hi there,

I'm a huge fan of rcrunchbase and its functionality, so thank you! I was just wondering if it is possible to access the "categories" parameter from a collection of organizations. I can't find it under any of the basic properties or the details properties, which seems odd. Is there an easy way to do this?

Thanks so much!

**Comment by tarakc02** [comment]
Hi Natalie, glad you like it! Each item in a collection of organizations is an "OrganizationSummary," and you can view the structure of an OrganizationSummary in the API documentation here: 

https://data.crunchbase.com/v3/docs/organizationsummary

It looks like there is not, in fact, a category (though you could get_details() on the items in the collection). I agree it seems odd, since you can filter on categories when doing an organizations query . . .. All of the slots in the OrganizationSummary are single-valued, so maybe that's why (an organization can have multiple categories).

**Comment by natalie-carlson** [comment]
Ah, thanks so much for the response! I finally found it, categories are
under relationships once you get_details()
(as $relationships$categories$items$properties.name). All this information
can be tricky to unpack, I really appreciate your help.

Best,
Natalie

**Comment by tarakc02** [comment]
Oh I see, I misunderstood the original question. Glad you were able to find it!
